import { NextResponse } from "next/server"

export async function GET(request) {
    const data = [
        {
            id: 1,
            imgSrc: "flashsale/flashsale-1.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 2,
            imgSrc: "flashsale/flashsale-2.jpg",
            isMallOri: true,
            isCashback: true,
            priceText: "Rp 20.000",
            hotText: "STOK TERBATAS",
            progress: 30,
            isOnFire: false,
        },
        {
            id: 3,
            imgSrc: "flashsale/flashsale-3.jpg",
            isMallOri: true,
            isCashback: true,
            priceText: "Rp 5.000",
            hotText: "337 TERJUAL",
            progress: 25,
            isOnFire: false,
        },
        {
            id: 4,
            imgSrc: "flashsale/flashsale-4.jpg",
            isMallOri: true,
            isCashback: true,
            priceText: "Rp 10.000",
            hotText: "STOK TERBATAS",
            progress: 10,
            isOnFire: true,
        },
        {
            id: 5,
            imgSrc: "flashsale/flashsale-5.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 6,
            imgSrc: "flashsale/flashsale-6.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 7,
            imgSrc: "flashsale/flashsale-7.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 8,
            imgSrc: "flashsale/flashsale-8.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 9,
            imgSrc: "flashsale/flashsale-9.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 10,
            imgSrc: "flashsale/flashsale-10.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 11,
            imgSrc: "flashsale/flashsale-11.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 12,
            imgSrc: "flashsale/flashsale-12.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 13,
            imgSrc: "flashsale/flashsale-13.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 14,
            imgSrc: "flashsale/flashsale-14.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 15,
            imgSrc: "flashsale/flashsale-15.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
        {
            id: 16,
            imgSrc: "flashsale/flashsale-16.jpg",
            isMallOri: true,
            isCashback: false,
            priceText: "Rp 17.000",
            hotText: "STOK TERBATAS",
            progress: 50,
            isOnFire: false,
        },
    ]

    return NextResponse.json(data)
}