export async function GET(request) {
    const data = [
        {
            id: 1,
            href: "/top-product/1",
            imgSrc: "produk-terlaris/produk-1.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 2,
            href: "top-product/2",
            imgSrc: "produk-terlaris/produk-2.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 3,
            href: "top-product/3",
            imgSrc: "produk-terlaris/produk-3.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 4,
            href: "top-product/4",
            imgSrc: "produk-terlaris/produk-4.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 5,
            href: "top-product/5",
            imgSrc: "produk-terlaris/produk-5.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 6,
            href: "top-product/6",
            imgSrc: "produk-terlaris/produk-6.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 7,
            href: "top-product/7",
            imgSrc: "produk-terlaris/produk-7.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 8,
            href: "top-product/8",
            imgSrc: "produk-terlaris/produk-8.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 9,
            href: "top-product/9",
            imgSrc: "produk-terlaris/produk-9.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 10,
            href: "top-product/10",
            imgSrc: "produk-terlaris/produk-10.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 11,
            href: "top-product/11",
            imgSrc: "produk-terlaris/produk-11.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 12,
            href: "top-product/12",
            imgSrc: "produk-terlaris/produk-12.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 13,
            href: "top-product/13",
            imgSrc: "produk-terlaris/produk-13.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 14,
            href: "top-product/14",
            imgSrc: "produk-terlaris/produk-14.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 15,
            href: "top-product/15",
            imgSrc: "produk-terlaris/produk-15.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 16,
            href: "top-product/16",
            imgSrc: "produk-terlaris/produk-16.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 17,
            href: "top-product/17",
            imgSrc: "produk-terlaris/produk-17.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 18,
            href: "top-product/18",
            imgSrc: "produk-terlaris/produk-18.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 19,
            href: "top-product/19",
            imgSrc: "produk-terlaris/produk-19.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
        {
            id: 20,
            href: "top-product/20",
            imgSrc: "produk-terlaris/produk-20.jpg",
            subText: "Penjualan / Bulan 207RB+",
            text: "Mukena Dewasa Khadijah",
        },
    ]

    return Response.json(data)
}