import { NextResponse } from "next/server"

export async function GET(request) {
    const data = [
        {
            id: 1,
            href: "product/1",
            recommendHref: "recommend/product/1",
            imgSrc: "produk-rekomendasi/produk-1.webp", 
            productText: "BASGOR / BAKSO GORENG", 
            promo: "promo",
            isMallOri: false, 
            isStar: true, 
            isTermurah: true, 
            isLokal: false, 
            isCOD: true,
            price: "20.000"
        },
        {
            id: 2,
            href: "product/2",
            recommendHref: "recommend/product/2",
            imgSrc: "produk-rekomendasi/produk-2.webp", 
            productText: "A-KEMOLA Sandal Jelly Baim Wedges", 
            promo: "p-lokal",
            isMallOri: false, 
            isStar: true, 
            isTermurah: false, 
            isLokal: false, 
            isCOD: true,
            price: "30.000"
        },
        {
            id: 3,
            href: "product/3",
            recommendHref: "recommend/product/3",
            imgSrc: "produk-rekomendasi/produk-3.webp", 
            productText: "Sandal Modern Minimalis", 
            promo: "p-ongkir",
            isMallOri: false, 
            isStar: true, 
            isTermurah: false, 
            isLokal: true, 
            isCOD: true,
            price: "30.000"
        },
        {
            id: 4,
            href: "product/4",
            recommendHref: "recommend/product/4",
            imgSrc: "produk-rekomendasi/produk-4.webp", 
            productText: "Celana Pendek Adidas Ori", 
            promo: "ongkir",
            isMallOri: true, 
            isStar: false, 
            isTermurah: false, 
            isLokal: false, 
            isCOD: true,
            price: "200.000"
        },
        {
            id: 5,
            href: "product/5",
            recommendHref: "recommend/product/5",
            imgSrc: "produk-rekomendasi/produk-5.webp", 
            productText: "1 pack pena / +12 batang", 
            promo: "p-ongkir",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: false, 
            isCOD: false,
            price: "12.000"
        },
        {
            id: 6,
            href: "product/6",
            recommendHref: "recommend/product/6",
            imgSrc: "produk-rekomendasi/produk-6.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
        {
            id: 7,
            href: "product/7",
            recommendHref: "recommend/product/7",
            imgSrc: "produk-rekomendasi/produk-7.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
        {
            id: 8,
            href: "product/8",
            recommendHref: "recommend/product/8",
            imgSrc: "produk-rekomendasi/produk-8.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
        {
            id: 9,
            href: "product/9",
            recommendHref: "recommend/product/9",
            imgSrc: "produk-rekomendasi/produk-9.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
        {
            id: 10,
            href: "product/10",
            recommendHref: "recommend/product/10",
            imgSrc: "produk-rekomendasi/produk-10.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
        {
            id: 11,
            href: "product/11",
            recommendHref: "recommend/product/11",
            imgSrc: "produk-rekomendasi/produk-11.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
        {
            id: 12,
            href: "product/12",
            recommendHref: "recommend/product/12",
            imgSrc: "produk-rekomendasi/produk-12.webp", 
            productText: "baju oblong kustom katun", 
            promo: "promo",
            isMallOri: false, 
            isStar: false, 
            isTermurah: true, 
            isLokal: true, 
            isCOD: false,
            price: "50.000"
        },
    ]

    return NextResponse.json(data)
}